### ISSUE TITLE
Lemmatisation: add abstraction layer

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [CondorCompPhil/collazione#12]
To use either Pie or Freeling, 
- [ ] add abstraction layer (function `lemmatise` and `lemmatise_pie`, `lemmatise_freeling`) in Python code.
- [ ] add options `--lemmatise fro` et `lemmatise_engine pie` to CLI.

**Comment by elespdn** [comment]
Distinguish text/txt/xml_raw vs text/xml_corr

**Comment by elespdn** [comment]
Add pie module for another language, even modern, and suitable example, for showcase

**Comment by elespdn** [comment]
For Pie can be more modular, with a lemmatise_pie module, taking as arguments the path and the language.
For Freeling it is more difficult, because the language is not enough: in the function there are plenty of paths to define together with the language. For example, for medieval Spanish some part of the lemmatizer seem to be missing so we use modern Spanish, as specified in the file.

So this means that there is only one file for lemmatization with pie for many language and potentially many files for many languages for Freeling.

I think it is ok for now, just a bit less elegant the Freeling part.
